{% set name = "db-dtypes" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db-dtypes-{{ version }}.tar.gz
  sha256: ee68f30cbccf343124ef0abebc7f8cc9a74ef8ed7ee4ff61f586117e8040a9d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - packaging >=17.0
    - pandas >=0.24.2,<2.0dev
    - pyarrow >=3.0.0
    - numpy >=1.16.6,<2.0dev

test:
  imports:
    - db_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  doc_url: https://googleapis.dev/python/db-dtypes/latest/index.html
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
