{% set name = "db-dtypes" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db_dtypes-{{ version }}.tar.gz
  sha256: 7bcbc8858b07474dc85b77bb2f3ae488978d1336f5ea73b58c39d9118bc3e91b

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging >=17.0
    - pandas >=0.24.2
    - pyarrow >=3.0.0
    - numpy >=1.16.6

test:
  source_files:
    - tests
  imports:
    - db_dtypes
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  description: |
    Pandas extension data types for data from SQL systems such as BigQuery.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://googleapis.dev/python/db-dtypes/latest/
  dev_url: https://github.com/googleapis/python-db-dtypes-pandas

extra:
  recipe-maintainers:
    - xylar
    - tswast
