{% set name = "db-dtypes" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db_dtypes-{{ version }}.tar.gz
  sha256: 7bcbc8858b07474dc85b77bb2f3ae488978d1336f5ea73b58c39d9118bc3e91b
  patches:                                                         # [py<39]
    # pandas 2.0.3 (last py38 build) does not support BaseReduceTests
    - patches/0001-remove-test-against-base.BaseReduceTests.patch  # [py<39]

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging >=17.0
    - pandas >=0.24.2
    - pyarrow >=3.0.0
    - numpy >=1.16.6

# pandas 2.0.3 (last py38 build) doesn't support this attribute
{% set tests_to_skip = "" %}
# AttributeError: 'JSONArray' object has no attribute '_data'
{% set tests_to_skip = tests_to_skip + "test_getitems_when_iter_with_null" %}   # [py<39]
{% set tests_to_skip = tests_to_skip + " or test_to_numpy" %}                   # [py<39]

{% set tests_to_skip = tests_to_skip + " or " %}                                # [py<39 and s390x]

# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
{% set tests_to_skip = tests_to_skip + "test_date_max_2d" %}                    # [s390x]
{% set tests_to_skip = tests_to_skip + " or test_date_min_2d" %}                # [s390x]
{% set tests_to_skip = tests_to_skip + " or test_date_median_2d" %}             # [s390x]
# AssertionError: assert array(...)
{% set tests_to_skip = tests_to_skip + " or test_asdatetime" %}                 # [s390x]


# pandas 2.0.3 (last py38 build) really doesn't like the JSON
# compliance tests, 325 of them
{% set tests_to_ignore = "" %}
# NotImplementedError: <class 'db_dtypes.json.JSONArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/compliance/json/test_json_compliance.py" %}  # [py<39]

test:
  source_files:
    - tests
  imports:
    - db_dtypes
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})" # [py<39]
    - pytest -v tests -k "not ({{ tests_to_skip }})"                       # [py>=39 and s390x]
    - pytest -v tests                                                      # [py>=39 and not s390x]

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  description: |
    Pandas extension data types for data from SQL systems such as BigQuery.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://googleapis.dev/python/db-dtypes/latest/
  dev_url: https://github.com/googleapis/python-db-dtypes-pandas

extra:
  recipe-maintainers:
    - xylar
    - tswast
