{% set name = "db-dtypes" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db-dtypes-{{ version }}.tar.gz
  sha256: 3070d1a8d86ff0b5d9b16f15c5fab9c18893c6b3d5723cd95ee397b169049454

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
  run:
    - numpy >=1.16.6,<2.0dev
    - packaging >=17.0
    - pandas >=0.24.2,<2.0dev
    - pyarrow >=3.0.0,<8.0dev
    - python >=3.6,<3.11

test:
  imports:
    - db_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  doc_url: https://googleapis.dev/python/db-dtypes/latest/index.html
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
